VIA_ENABLE=yes
VIAL_ENABLE=yes
LTO_ENABLE=yes
CONSOLE_ENABLE=yes
EXTRAKEY_ENABLE=yes
ENCODER_ENABLE=yes
ENCODER_MAP_ENABLE=yes
VIAL_INSECURE=yes

WPM_ENABLE = yes
OLED_ENABLE=yes

DEFERRED_EXEC_ENABLE = yes
